### YAML file to easily specify and modify hyperparameters used in main_training_script ###

experiment_name: "vgg16"
saving_frequency: 5
data_preprocess: true


model:
  name: "vgg16"
  pretrained: true

pretrain_source: "imagenet"
batch_size: 32
num_epochs: 200

optimizer_lr: 0.01
