### YAML file to easily specify and modify hyperparameters used in main_training_script ###

experiment_name: "bilbily"
saving_frequency: 5


model:
  name: "bilbily"
  pretrained: false
  sex_encoding: "binary"

pretrain_source: "imagenet"
batch_size: 32
num_epochs: 200

optimizer_lr: 0.01
